name: coffee
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  json_annotation: ^4.0.1
  json_serializable: ^4.1.3
  build_runner: ^2.0.5
  flutter_bloc: ^7.0.1
  bloc: ^7.0.0
  firebase_core: ^1.3.0
  firebase_auth: ^2.0.0
  provider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
